In [6]:
import pandas as pd
from selenium import webdriver

import time
from tqdm import tqdm
import regex as re
import warnings
warnings.filterwarnings('ignore')

In [7]:
data= pd.read_excel('temperaturas.xlsx')

In [8]:
data.describe().T

        count       mean       std   min   25%   50%   75%   max
ciudad   33.0  17.000000  9.669540   1.0   9.0  17.0  25.0  33.0
ene      33.0   2.400000  3.866685  -3.3  -0.2   1.9   4.7  12.0
feb      33.0   4.536364  4.006621  -2.2   2.2   4.7   6.9  13.8
mer      33.0   5.306061  3.447004  -0.3   2.7   5.2   7.4  13.8
abr      33.0   9.239394  3.534733   3.3   6.9   9.4  11.6  17.0
may      33.0  15.378788  3.837541   7.9  12.1  16.0  18.3  21.6
jun      33.0  20.057576  3.841064   9.9  17.4  19.9  22.8  27.1
jul      33.0  21.315152  4.095128  10.8  18.1  21.8  24.6  29.2
ago      33.0  21.651515  3.556255  10.5  20.2  21.6  23.8  28.2
sep      33.0  15.230303  4.365095   9.0  12.6  15.1  17.4  25.9
oct      33.0  12.836364  3.936037   5.1  11.2  12.6  14.3  21.6
nov      33.0   7.354545  3.991717   1.4   4.4   6.9   9.1  18.0
dic      33.0   2.654545  5.134448  -6.7   0.4   2.3   5.7  13.8